Add .editorconfig file
DevChatter/Smilodon pull request #27
Opened 2022-11-25 23:18 UTC by kirkbrauer

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #26 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested in JetBrains Rider

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-11-25 23:20 UTC, kirkbrauer commented
I made some specific opinionated decisions for this, but most of it is just the .NET template. Main differences is that we are not using UTF-8 BOM, since that is no longer recommended. I have also forced LF line endings for all `.cs` files, so there won't be confusion between Unix and Windows systems (even though this is addressed in `.gitattributes` as well.

2022-11-26 00:35 UTC, benrick requested changes
Looks good. I do think we should refrain form too much `var` though, since it makes it easier for new viewers to know the types of variables.

I put it to `suggestion`, which is the MS default for elsewhere and built-in types. If we run into an issue with those, we can switch it to silent.

2022-11-26 00:35 UTC, benrick commented on .editorconfig
> +csharp_style_var_elsewhere = true:silent
```suggestion
# var preferences
csharp_style_var_for_built_in_types = false:suggestion
csharp_style_var_when_type_is_apparent = true:silent
csharp_style_var_elsewhere = false:suggestion
```

Matching dotnet style guide here.

2022-11-26 00:41 UTC, kirkbrauer commented
@benrick ah, good idea. I tend to prefer var for pretty much everything, however it should be strongly avoided if the RHS type is unknown (a complex expression or LINQ statement) or null. Suggestion should work, we'll see if it causes any roadblocks.

2022-11-26 00:43 UTC, benrick commented
> @benrick ah, good idea. I tend to prefer var for pretty much everything, however it should be strongly avoided if the RHS type is unknown (a complex expression or LINQ statement) or null. Suggestion should work, we'll see if it causes any roadblocks.

Yeah, I'm kind of surprised that the example in the docs has as many deviations from the style guide from MS. I might have to send them a PR to fix that sample to align with their own standards!

2022-11-26 00:46 UTC, kirkbrauer commented
@benrick  Yeah, I wasn't paying too much attention to that, I just had assumed they would be consistent lol. I do however see a lot of var in the docs and their official tutorials. For an OSS project as long as we're consistent it doesn't matter except for the scenarios I mentioned above.

2022-11-26 01:02 UTC, benrick commented
> @benrick Yeah, I wasn't paying too much attention to that, I just had assumed they would be consistent lol. I do however see a lot of var in the docs and their official tutorials. For an OSS project as long as we're consistent it doesn't matter except for the scenarios I mentioned above.

Yeah, I usually try to discourage those overly complex types where possible anyway, so hopefully we don't need the `var` for those too often! 🤣

2022-11-26 01:06 UTC, benrick approved these changes
Looks like a good enough start. Let's plan on tweaking and adjusting as we go.

2022-11-26 01:07 UTC, merged